#%RAML 1.0 Trait
responses:

  200:
    body:
      application/json:
        example:
          {"OK"}
  204:
    body:
      application/json:
        example:
          {"No content"}
  203:
    body:
      application/json:
        example:
          {"Non-Authoritative Information"} 