#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example:
          [{"id": 4088,
          "name":"Red Pepper",
          "rate":"3.99",
          "barecode":"9876",
          "catagories":"Vegitables"}]
  400:
    body:
      application/json:
        example:
          {"error":"Bad Request"} 